FROM node:22-slim AS setup

ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"

RUN npm install -g corepack@0.20
RUN corepack enable

WORKDIR /app

COPY . .
COPY .env.dev .env

RUN pnpm install

CMD pnpm run dev