{
 "title": "Business Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "rate_interval", "label": "Rate Interval", "query": "1m,5m,15m,30m,1h,6h,1d" }
  ]
 },
 "panels": [
  { "title": "Bookings", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Всего бронирований",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "targets": [
    { "expr": "sum(new_bookings_total)", "legendFormat": "Total New Bookings" }
   ]
  },
  {
   "title": "Частота новых бронирований",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(new_bookings_total[$rate_interval]))",
     "legendFormat": "Bookings Rate"
    }
   ]
  },
  {
   "title": "Бронирования по местам",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(new_bookings_total) by (place_id)",
     "legendFormat": "{{place_id}}"
    }
   ]
  },
  {
   "title": "Частота бронирования по местам",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(new_bookings_total[$rate_interval])) by (place_id)",
     "legendFormat": "{{place_id}}"
    }
   ]
  },
  {
   "title": "Бронирования по пользователю",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 20 },
   "repeat": "user_id",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (user_id) (new_bookings_total)",
     "legendFormat": "{{user_id}}"
    }
   ]
  },
  {
   "title": "Бронирования по ролям",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(new_bookings_total) by (role)",
     "legendFormat": "{{role}}"
    }
   ]
  },
  {
   "title": "Visits",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Visits",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 132 },
     "targets": [
      { "expr": "sum(bookings_activated_total)", "legendFormat": "Total Visits" }
     ]
    },
    {
     "title": "Visits Rate",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 132 },
     "targets": [
      {
       "expr": "sum(rate(bookings_activated_total[$rate_interval]))",
       "legendFormat": "Visits Rate"
      }
     ]
    },
    {
     "title": "Visits by Place",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 141 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(bookings_activated_total) by (place_id)",
       "legendFormat": "{{place_id}}"
      }
     ]
    },
    {
     "title": "Visits rate by Place",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 141 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(bookings_activated_total[$rate_interval])) by (place_id)",
       "legendFormat": "{{place_id}}"
      }
     ]
    },
    {
     "title": "Top visits by User",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 149 },
     "repeat": "user_id",
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (user_id) (bookings_activated_total)",
       "legendFormat": "{{user_id}}"
      }
     ]
    },
    {
     "title": "Visits by Role",
     "type": "piechart",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 157 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(bookings_activated_total) by (role)",
       "legendFormat": "{{role}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Conversion",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 },
   "collapsed": true,
   "panels": [
    {
     "title": "Place Conversion Rate",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 81 },
     "repeat": "place_id",
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "sum by (place_id) (bookings_activated_total) / sum by (place_id) (new_bookings_total)",
       "legendFormat": "{{place_id}}"
      }
     ]
    },
    {
     "title": "User Conversion Rate",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 89 },
     "repeat": "user_id",
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (user_id) (bookings_activated_total) / sum by (user_id) (new_bookings_total)",
       "legendFormat": "{{user_id}}"
      }
     ]
    }
   ]
  }
 ]
}