"""add secret id

Revision ID: 800d0ba2c022
Revises: bb5422d3583d
Create Date: 2025-03-02 12:52:21.312533

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = "800d0ba2c022"
down_revision = "bb5422d3583d"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("booking", "date", existing_type=postgresql.TIMESTAMP(), type_=sa.Date(), existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("booking", "date", existing_type=sa.Date(), type_=postgresql.TIMESTAMP(), existing_nullable=False)
    # ### end Alembic commands ###
