"""fix relationships

Revision ID: a58217dcfd9d
Revises: 2fd80b4b5d14
Create Date: 2025-03-01 09:06:10.248315

"""

revision = "a58217dcfd9d"
down_revision = "2fd80b4b5d14"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
