"""fix place

Revision ID: bb5422d3583d
Revises: a58217dcfd9d
Create Date: 2025-03-01 12:37:55.456712

"""

import uuid
from datetime import date, timedelta

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = "bb5422d3583d"
down_revision = "a58217dcfd9d"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("booking", sa.Column("date", sa.DateTime(), nullable=False))
    op.add_column("booking", sa.Column("start_second", sa.Integer(), nullable=False))
    op.add_column("booking", sa.Column("end_second", sa.Integer(), nullable=False))
    op.drop_column("booking", "end_date")
    op.drop_column("booking", "start_date")

    booking_table = sa.Table("booking", sa.MetaData(), autoload_with=op.get_bind())

    booking_table = sa.Table("booking", sa.MetaData(), autoload_with=op.get_bind())

    day1 = date.today()
    day2 = day1 + timedelta(days=1)
    day3 = day1 + timedelta(days=2)

    data = [
        {
            "id": str(uuid.uuid4()),
            "user_id": "081cd80a-4ce4-41ab-ac2b-7c6e0ec200a9",  # guest
            "place_id": "a6abc93b-5c12-47b2-b1b4-01ba1ece6dda",  # стол 3
            "date": day1,
            "start_second": 9 * 3600,
            "end_second": 10 * 3600,
            "is_activated_by_user": False,
            "notified_start": False,
            "notified_end": False,
        },
        {
            "id": str(uuid.uuid4()),
            "user_id": "6b908b52-f4e0-4ce8-a8db-ee0e9609521e",  # student
            "place_id": "a6abc93b-5c12-47b2-b1b4-01ba1ece6dda",  # стол 3
            "date": day1,
            "start_second": 10 * 3600 + 1,
            "end_second": 11 * 3600,
            "is_activated_by_user": False,
            "notified_start": False,
            "notified_end": False,
        },
        {
            "id": str(uuid.uuid4()),
            "user_id": "6b908b52-f4e0-4ce8-a8db-ee0e9609521e",  # student
            "place_id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",  # Стол 1
            "date": day2,
            "start_second": 9 * 3600,
            "end_second": 10 * 3600,
            "is_activated_by_user": False,
            "notified_start": False,
            "notified_end": False,
        },
        {
            "id": str(uuid.uuid4()),
            "user_id": "081cd80a-4ce4-41ab-ac2b-7c6e0ec200a9",  # guest
            "place_id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",  # Стол 1
            "date": day1,
            "start_second": 18 * 3600,
            "end_second": 19 * 3600,
            "is_activated_by_user": False,
            "notified_start": False,
            "notified_end": False,
        },
        {
            "id": str(uuid.uuid4()),
            "user_id": "6b908b52-f4e0-4ce8-a8db-ee0e9609521e",  # student
            "place_id": "c8b70475-af22-4991-8d51-442ab164b1d9",  # Стол 2
            "date": day3,
            "start_second": 9 * 3600,
            "end_second": 10 * 3600,
            "is_activated_by_user": False,
            "notified_start": False,
            "notified_end": False,
        },
        {
            "id": str(uuid.uuid4()),
            "user_id": "6b908b52-f4e0-4ce8-a8db-ee0e9609521e",  # student
            "place_id": "c8b70475-af22-4991-8d51-442ab164b1d9",  # Стол 2
            "date": day3,
            "start_second": 17 * 3600,
            "end_second": 18 * 3600,
            "is_activated_by_user": False,
            "notified_start": False,
            "notified_end": False,
        },
        {
            "id": str(uuid.uuid4()),
            "user_id": "081cd80a-4ce4-41ab-ac2b-7c6e0ec200a9",  # guest
            "place_id": "c8b70475-af22-4991-8d51-442ab164b1d9",  # Стол 2
            "date": day1,
            "start_second": 16 * 3600,
            "end_second": 17 * 3600,
            "is_activated_by_user": False,
            "notified_start": False,
            "notified_end": False,
        },
    ]

    op.bulk_insert(booking_table, data)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("place", "name")
    op.add_column("booking", sa.Column("start_date", postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column("booking", sa.Column("end_date", postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column("booking", "end_second")
    op.drop_column("booking", "start_second")
    op.drop_column("booking", "date")
    # ### end Alembic commands ###
